- name: Add emqx chart repository
  kubernetes.core.helm_repository:
    name: emqx
    repo_url: https://repos.emqx.io/charts
    force_update: true

- name: Install emqx operator
  kubernetes.core.helm:
    name: emqx
    chart_ref: emqx/emqx-operator
    release_namespace: emqx
    create_namespace: true
    update_repo_cache: true
    wait: true

- name: Wait emqx operator pod
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - control-plane=controller-manager
    namespace: emqx
    wait: true
    wait_condition:
      type: Ready
  register: result

- name: Check if emqx operator pod is running
  fail:
    msg: "EMQX operator installation failed. Expected 1 pod, found {{ result.resources | length }}."
  when: result.resources | length != 1
