- name: Add clickhouse chart repository
  kubernetes.core.helm_repository:
    name: clickhouse
    repo_url: https://charts.bitnami.com/bitnami
    force_update: true

- name: Install clickhouse
  kubernetes.core.helm:
    name: clickhouse
    chart_ref: clickhouse/clickhouse
    release_namespace: clickhouse
    create_namespace: true
    update_repo_cache: true
    wait: true
    values:
      shards: "{{ clickhouse_shards }}"
      replicaCount: "{{ clickhouse_replicas }}"
      auth:
        username: "{{ clickhouse_auth_username }}"
        password: "{{ clickhouse_auth_password }}"
      resources:
        requests:
          cpu: 1
          memory: 512Mi
        limits:
          cpu: 2
          memory: 2048Mi