rook_ceph_operator_version: "1.17.4"
rook_ceph_cluster_version: "1.17.4"

rook_ceph_namespace: "rook-ceph"
rook_ceph_cluster_name: "rook-ceph"

ceph_image: "quay.io/ceph/ceph:v19.2.1"

mon_count: 3
mon_allow_multiple_per_node: false

mgr_count: 2
mgr_allow_multiple_per_node: false

dashboard_enabled: true
dashboard_ssl: false
prometheus_endpoint: ""

objectstore_name: "ceph-objectstore"
objectstore_gateway_port: 80
objectstore_instances: 2
objectstore_resources:
  requests:
    cpu: "1000m"
    memory: "1Gi"

objectstore_storage_class_enabled: true
objectstore_storage_class_name: "rook-ceph-bucket"
objectstore_storage_class_reclaim_policy: "Delete"
objectstore_storage_class_volume_binding_mode: "Immediate"

storage_use_all_nodes: true
storage_use_all_devices: false
storage_allow_device_class_update: true
storage_allow_osd_crush_weight_update: true

objectstore_metadata_pool_size: 3
objectstore_data_pool_size: 3

mgr_pool_size: 3

monitoring_enabled: true
create_prometheus_rules: true

csi_enable_rbd_driver: false
csi_enable_cephfs_driver: false
csi_enable_rbd_snapshotter: false
csi_enable_cephfs_snapshotter: false
csi_enable_nfs_snapshotter: false
csi_provisioner_replicas: 1
csi_plugin_selinux_host_mount: false
csi_encryption_enabled: false

csi_resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

rook_log_level: "INFO"
rook_operator_metrics_bind_address: "0"
rook_ceph_allow_loop_devices: "false"
rook_use_csi_operator: "false"

skip_upgrade_checks: true
crash_collector_disable: false
health_check_daemon_health_mon_interval: "45s"
health_check_daemon_health_mon_timeout: "25s"
priority_class_names_all: "system-node-critical"
priority_class_names_mgr: "system-cluster-critical"
disruption_management_manage_pod_budgets: true

ceph_config_global_osd_pool_default_size: "3"
ceph_config_global_osd_pool_default_min_size: "2"
ceph_config_global_mon_warn_on_pool_no_redundancy: "true"
ceph_config_global_bdev_flock_retry: "3"
ceph_config_global_bluefs_buffered_io: "true"
ceph_config_global_mon_data_avail_warn: "15"

network_encryption_enabled: true
network_compression_enabled: true
network_require_msgr2: true

toolbox_enabled: true
toolbox_replicas: 1
toolbox_image: "quay.io/ceph/ceph:v19.2.1"
toolbox_image_pull_policy: "IfNotPresent"
toolbox_dns_policy: "ClusterFirstWithHostNet"
toolbox_service_account_name: "rook-ceph-default"
toolbox_security_context:
  runAsNonRoot: true
  runAsUser: 2016
  runAsGroup: 2016
  capabilities:
    drop: ["ALL"]
toolbox_tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 5
