- name: Install local-path-provisioner
  hosts: localhost
  roles:
    - localpath

- name: Install gateway api
  hosts: localhost
  roles:
    - gateway

- name: Install certmanager
  hosts: localhost
  roles:
    - certmanager/install

- name: Install self-signed cluster issuer
  hosts: localhost
  roles:
    - certmanager/selfsigned

- name: Install minio
  hosts: localhost
  roles:
    - minio

- name: Install clickhouse
  hosts: localhost
  roles:
    - clickhouse

- name: Install greptimedb
  hosts: localhost
  roles:
    - greptimedb

- name: Install quickwit
  hosts: localhost
  roles:
    - quickwit

- name: Install opentelemetry
  hosts: localhost
  roles:
    - opentelemetry

- name: Install grafana
  hosts: localhost
  roles:
    - grafana
