- name: Add cilium chart repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{cilium_version}}"
    release_namespace: kube-system
    values:
      k8sServiceHost: "{{k8s_apiserver_ip}}"
      k8sServicePort: 6443
      routingMode: native
      tunnelProtocol:
      kubeProxyReplacement: true
      autoDirectNodeRoutes: true
      installIptablesRules: true
      l7Proxy: false
      enableCnpStatusUpdates: false
      endpointRoutes:
        enabled: true
      bpf:
        masquerade: true
      masquerade: true
      localRedirectPolicy: true
      ipv4NativeRoutingCIDR: "{{k8s_pod_subnet}}"
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList:
            - "{{k8s_pod_subnet}}"
          clusterPoolIPv4MaskSize: "{{k8s_pod_subnet_masksize}}"
      logOptions:
        format: json

- name: Wait cilium pod
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - k8s-app=cilium
    namespace: kube-system
    wait: true
    wait_condition:
      type: Ready
