- name: Add opentelemetry chart repository
  kubernetes.core.helm_repository:
    name: open-telemetry
    repo_url: https://open-telemetry.github.io/opentelemetry-helm-charts
    force_update: true

- name: Install opentelemetry
  kubernetes.core.helm:
    name: otel-collector
    chart_ref: open-telemetry/opentelemetry-collector
    release_namespace: opentelemetry
    create_namespace: true
    values:
      mode: daemonset
      image:
        repository: otel/opentelemetry-collector-k8s
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      presets:
        logsCollection:
          enabled: true
        kubernetesAttributes:
          enabled: true
        kubeletMetrics:
          enabled: true
        hostMetrics:
          enabled: true
      config:
        exporters:
          otlp/quickwit:
            endpoint: quickwit-indexer.quickwit.svc.cluster.local:7281
            tls:
              insecure: true
            headers:
              qw-otel-logs-index: otel-logs-v0_7
          clickhouse:
            endpoint: tcp://localhost:9000?dial_timeout=10s&compress=lz4&async_insert=1
            traces_table_name: otel_traces
            logs_table_name: otel_logs
            create_schema: true
            timeout: 5s
            database: default
            sending_queue:
              queue_size: 1000
            retry_on_failure:
              enabled: true
              initial_interval: 5s
              max_interval: 30s
              max_elapsed_time: 300s
          debug:
            verbosity: detailed
        receivers:
          kubeletstats:
            collection_interval: 10s
            auth_type: "serviceAccount"
            insecure_skip_verify: true
        processors:
          attributes/node:
            actions:
              - key: node
                value: ${env:K8S_NODE_NAME}
                action: upsert
        service:
          pipelines:
            logs:
              exporters:
                - otlp/quickwit
            metrics:
              processors:
                - attributes/node
              exporters:
                - clickhouse
