- name: Add prometheus chart repository
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus/prometheus
    release_namespace: prometheus
    create_namespace: true
    values:
      server:
        extraFlags:
          - web.enable-lifecycle
          - web.enable-otlp-receiver
      alertmanager:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
      prometheus-pushgateway:
        enabled: false
