apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: s3secrets
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: S3_SECRET_KEY
