- name: Add external-secrets chart repository
  kubernetes.core.helm_repository:
    name: external-secrets
    repo_url: https://charts.external-secrets.io
    force_update: true

- name: Install external-secrets
  kubernetes.core.helm:
    name: external-secrets
    chart_ref: external-secrets/external-secrets
    release_namespace: external-secrets
    create_namespace: true
