- name: Install self-signed cluster issuer
  kubernetes.core.k8s:
    state: present
    template: selfsigned.yaml.j2

- name: Wait self-signed cluster issuer
  kubernetes.core.k8s_info:
    kind: ClusterIssuer
    name: selfsigned
    wait: true
    wait_condition:
      type: Ready
  register: result

- name: Check if self-signed cluster issuer is ready
  fail:
    msg: "Self-signed cluster issuer installation failed. Expected 1 resource, found {{ result.resources | length }}."
  when: result.resources | length != 1
